version: 2
project_name: todo

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: todo-linux
    env:
      - CGO_ENABLED=1
    main: ./main.go
    binary: todo
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - 386
    overrides:
      - goarch: amd64
        env:
          - CC=gcc
          - CXX=g++
      - goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goarch: 386
        env:
          - CC=i686-linux-gnu-gcc
          - CXX=i686-linux-gnu-g++

  - id: todo-darwin
    env:
      - CGO_ENABLED=1
    main: ./main.go
    binary: todo
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goarch: 386

  - id: todo-windows
    env:
      - CGO_ENABLED=1
    main: ./main.go
    binary: todo
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    goos:
      - windows
    goarch:
      - amd64
      - 386
    overrides:
      - goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
      - goarch: 386
        env:
          - CC=i686-w64-mingw32-gcc
          - CXX=i686-w64-mingw32-g++

checksum:
  name_template: >-
    todo_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}
    _checksums.txt
  algorithm: sha256
  split: true

archives:
  - id: default
    formats: [ tar.gz ]
    name_template: >-
      todo_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  mode: append
  footer: |-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).