version: 2
project_name: todo

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: todo
    env:
      - CGO_ENABLED=1

    main: ./main.go
    binary: todo
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

checksum:
  name_template: >-
    todo_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}
    _checksums.txt
  algorithm: sha256
  split: true

archives:
  - id: default
    formats: [ tar.gz ]

    name_template: >-
      todo_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  mode: append
  footer: |-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
